version: 0.2

phases:
  install:
     pre_build:
    commands:
      - echo "Installing dependencies..." 
      - pip install -r 
  build:
    commands:
      - cd DA
      - echo "Building Docker image..."
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../DA
