version: 0.2

phases:
  install:
     pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 557690608241.dkr.ecr.ap-southeast-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=557690608241.dkr.ecr.ap-southeast-1.amazonaws.com/da-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Installing dependencies..." 
      - npm install
  build:
    commands:
      - cd DA
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest  .
      - docker push $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../DA
