version: 0.2
phases:
  pre_build:
    commands:
      #- echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 557690608241.dkr.ecr.ap-southeast-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=557690608241.dkr.ecr.ap-southeast-1.amazonaws.com/da-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files: []
   
