apiVersion: apps/v1
kind: Deployment
metadata:
  name: da-demo-ecr
  labels:
    app: da-demo-ecr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da-demo-ecr
  template:
    metadata:
      labels:
        app: da-demo-ecr
    spec:
      containers:
        - name: da-demo-ecr
          image: 557690608241.dkr.ecr.ap-southeast-1.amazonaws.com/da-demo-ecr:1.1
          ports:
            - containerPort: 80
